// examples/react-webpack/src/App.js
import './superhero-utils/index.css';
import { Button as SuperheroButton } from './superhero-utils/react-without-styles.js';

import './style.css';

function App() {
  return (
    <div className="Example-List">
      <h3>superhero-utils example using react, webpack</h3>
      medium:
      <SuperheroButton size="medium" account="ak_... or .chain name" />

      {['large', 'small', 'icon'].map(size =>
        <>
          {size}:
          <SuperheroButton size={size} account="ak_... or .chain name" />
        </>
      )}
    </div>
  );
}

export default App;

// examples/vue-webpack/src/App.vue
<template>
  <div>
    <h3>superhero-utils example using vue, webpack</h3>
    <SuperheroButton size="medium" account="ak_... or .chain name" />
  </div>
</template>

<script>
import '../../superhero-utils/index.css';
import { Button } from '../../superhero-utils/vue-without-styles.js';

export default {
  components: {
    SuperheroButton: Button,
  },
};
</script>
