// examples/vue-vite/src/App.vue
<template>
  <div>
    <h3>superhero-utils example using vue, vite</h3>
    <superhero-button
      size="medium"
      target="ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc"
    ></superhero-button>
  </div>
</template>

<script>
import '../../superhero-utils/index.css';
import '../../superhero-utils/index-without-styles.js';

export default {};
</script>

// examples/react-vite/src/App.jsx
import '../../superhero-utils/index.css';
import '../../superhero-utils/index-without-styles.js';

function App() {
  return (
    <div>
      <h3>superhero-utils example using react, vite</h3>
      <superhero-button
        size="medium"
        target="ak_gvxNbZf5CuxYVfcUFoKAP4geZatWaC2Yy4jpx5vZoCKank4Gc"
      />
    </div>
  );
}

export default App;
